// <auto-generated />
using System;
using HotelDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelDashboard.Data.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20200713215027_Relationships changed")]
    partial class Relationshipschanged
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HotelDashboard.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomStatusId")
                        .HasColumnType("int");

                    b.Property<string>("SecondName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoomStatusId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("HotelDashboard.Data.Models.Corps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Corps");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        });
                });

            modelBuilder.Entity("HotelDashboard.Data.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CorpsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CorpsId");

                    b.ToTable("Floors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorpsId = 1
                        },
                        new
                        {
                            Id = 2,
                            CorpsId = 1
                        },
                        new
                        {
                            Id = 3,
                            CorpsId = 1
                        },
                        new
                        {
                            Id = 4,
                            CorpsId = 1
                        },
                        new
                        {
                            Id = 5,
                            CorpsId = 1
                        },
                        new
                        {
                            Id = 6,
                            CorpsId = 1
                        },
                        new
                        {
                            Id = 7,
                            CorpsId = 1
                        },
                        new
                        {
                            Id = 8,
                            CorpsId = 1
                        },
                        new
                        {
                            Id = 9,
                            CorpsId = 2
                        },
                        new
                        {
                            Id = 10,
                            CorpsId = 2
                        },
                        new
                        {
                            Id = 11,
                            CorpsId = 2
                        },
                        new
                        {
                            Id = 12,
                            CorpsId = 2
                        },
                        new
                        {
                            Id = 13,
                            CorpsId = 2
                        },
                        new
                        {
                            Id = 14,
                            CorpsId = 2
                        },
                        new
                        {
                            Id = 15,
                            CorpsId = 2
                        },
                        new
                        {
                            Id = 16,
                            CorpsId = 2
                        },
                        new
                        {
                            Id = 17,
                            CorpsId = 3
                        },
                        new
                        {
                            Id = 18,
                            CorpsId = 3
                        },
                        new
                        {
                            Id = 19,
                            CorpsId = 3
                        },
                        new
                        {
                            Id = 20,
                            CorpsId = 3
                        },
                        new
                        {
                            Id = 21,
                            CorpsId = 3
                        },
                        new
                        {
                            Id = 22,
                            CorpsId = 3
                        },
                        new
                        {
                            Id = 23,
                            CorpsId = 3
                        },
                        new
                        {
                            Id = 24,
                            CorpsId = 3
                        },
                        new
                        {
                            Id = 25,
                            CorpsId = 4
                        },
                        new
                        {
                            Id = 26,
                            CorpsId = 4
                        },
                        new
                        {
                            Id = 27,
                            CorpsId = 4
                        },
                        new
                        {
                            Id = 28,
                            CorpsId = 4
                        },
                        new
                        {
                            Id = 29,
                            CorpsId = 4
                        },
                        new
                        {
                            Id = 30,
                            CorpsId = 4
                        },
                        new
                        {
                            Id = 31,
                            CorpsId = 4
                        },
                        new
                        {
                            Id = 32,
                            CorpsId = 4
                        });
                });

            modelBuilder.Entity("HotelDashboard.Data.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FloorId = 1,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            FloorId = 1,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            FloorId = 1,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            FloorId = 1,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            FloorId = 1,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 6,
                            FloorId = 1,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 7,
                            FloorId = 1,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 8,
                            FloorId = 1,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 9,
                            FloorId = 1,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 10,
                            FloorId = 1,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 11,
                            FloorId = 2,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 12,
                            FloorId = 2,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 13,
                            FloorId = 2,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 14,
                            FloorId = 2,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 15,
                            FloorId = 2,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 16,
                            FloorId = 2,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 17,
                            FloorId = 2,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 18,
                            FloorId = 2,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 19,
                            FloorId = 2,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 20,
                            FloorId = 2,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 21,
                            FloorId = 3,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 22,
                            FloorId = 3,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 23,
                            FloorId = 3,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 24,
                            FloorId = 3,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 25,
                            FloorId = 3,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 26,
                            FloorId = 3,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 27,
                            FloorId = 3,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 28,
                            FloorId = 3,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 29,
                            FloorId = 3,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 30,
                            FloorId = 3,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 31,
                            FloorId = 4,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 32,
                            FloorId = 4,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 33,
                            FloorId = 4,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 34,
                            FloorId = 4,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 35,
                            FloorId = 4,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 36,
                            FloorId = 4,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 37,
                            FloorId = 4,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 38,
                            FloorId = 4,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 39,
                            FloorId = 4,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 40,
                            FloorId = 4,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 41,
                            FloorId = 5,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 42,
                            FloorId = 5,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 43,
                            FloorId = 5,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 44,
                            FloorId = 5,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 45,
                            FloorId = 5,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 46,
                            FloorId = 5,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 47,
                            FloorId = 5,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 48,
                            FloorId = 5,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 49,
                            FloorId = 5,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 50,
                            FloorId = 5,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 51,
                            FloorId = 6,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 52,
                            FloorId = 6,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 53,
                            FloorId = 6,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 54,
                            FloorId = 6,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 55,
                            FloorId = 6,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 56,
                            FloorId = 6,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 57,
                            FloorId = 6,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 58,
                            FloorId = 6,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 59,
                            FloorId = 6,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 60,
                            FloorId = 6,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 61,
                            FloorId = 7,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 62,
                            FloorId = 7,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 63,
                            FloorId = 7,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 64,
                            FloorId = 7,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 65,
                            FloorId = 7,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 66,
                            FloorId = 7,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 67,
                            FloorId = 7,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 68,
                            FloorId = 7,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 69,
                            FloorId = 7,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 70,
                            FloorId = 7,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 71,
                            FloorId = 8,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 72,
                            FloorId = 8,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 73,
                            FloorId = 8,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 74,
                            FloorId = 8,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 75,
                            FloorId = 8,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 76,
                            FloorId = 8,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 77,
                            FloorId = 8,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 78,
                            FloorId = 8,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 79,
                            FloorId = 8,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 80,
                            FloorId = 8,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 81,
                            FloorId = 9,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 82,
                            FloorId = 9,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 83,
                            FloorId = 9,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 84,
                            FloorId = 9,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 85,
                            FloorId = 9,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 86,
                            FloorId = 9,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 87,
                            FloorId = 9,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 88,
                            FloorId = 9,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 89,
                            FloorId = 9,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 90,
                            FloorId = 9,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 91,
                            FloorId = 10,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 92,
                            FloorId = 10,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 93,
                            FloorId = 10,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 94,
                            FloorId = 10,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 95,
                            FloorId = 10,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 96,
                            FloorId = 10,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 97,
                            FloorId = 10,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 98,
                            FloorId = 10,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 99,
                            FloorId = 10,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 100,
                            FloorId = 10,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 101,
                            FloorId = 11,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 102,
                            FloorId = 11,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 103,
                            FloorId = 11,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 104,
                            FloorId = 11,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 105,
                            FloorId = 11,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 106,
                            FloorId = 11,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 107,
                            FloorId = 11,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 108,
                            FloorId = 11,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 109,
                            FloorId = 11,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 110,
                            FloorId = 11,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 111,
                            FloorId = 12,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 112,
                            FloorId = 12,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 113,
                            FloorId = 12,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 114,
                            FloorId = 12,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 115,
                            FloorId = 12,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 116,
                            FloorId = 12,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 117,
                            FloorId = 12,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 118,
                            FloorId = 12,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 119,
                            FloorId = 12,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 120,
                            FloorId = 12,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 121,
                            FloorId = 13,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 122,
                            FloorId = 13,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 123,
                            FloorId = 13,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 124,
                            FloorId = 13,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 125,
                            FloorId = 13,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 126,
                            FloorId = 13,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 127,
                            FloorId = 13,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 128,
                            FloorId = 13,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 129,
                            FloorId = 13,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 130,
                            FloorId = 13,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 131,
                            FloorId = 14,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 132,
                            FloorId = 14,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 133,
                            FloorId = 14,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 134,
                            FloorId = 14,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 135,
                            FloorId = 14,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 136,
                            FloorId = 14,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 137,
                            FloorId = 14,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 138,
                            FloorId = 14,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 139,
                            FloorId = 14,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 140,
                            FloorId = 14,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 141,
                            FloorId = 15,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 142,
                            FloorId = 15,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 143,
                            FloorId = 15,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 144,
                            FloorId = 15,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 145,
                            FloorId = 15,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 146,
                            FloorId = 15,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 147,
                            FloorId = 15,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 148,
                            FloorId = 15,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 149,
                            FloorId = 15,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 150,
                            FloorId = 15,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 151,
                            FloorId = 16,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 152,
                            FloorId = 16,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 153,
                            FloorId = 16,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 154,
                            FloorId = 16,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 155,
                            FloorId = 16,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 156,
                            FloorId = 16,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 157,
                            FloorId = 16,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 158,
                            FloorId = 16,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 159,
                            FloorId = 16,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 160,
                            FloorId = 16,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 161,
                            FloorId = 17,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 162,
                            FloorId = 17,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 163,
                            FloorId = 17,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 164,
                            FloorId = 17,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 165,
                            FloorId = 17,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 166,
                            FloorId = 17,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 167,
                            FloorId = 17,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 168,
                            FloorId = 17,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 169,
                            FloorId = 17,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 170,
                            FloorId = 17,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 171,
                            FloorId = 18,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 172,
                            FloorId = 18,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 173,
                            FloorId = 18,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 174,
                            FloorId = 18,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 175,
                            FloorId = 18,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 176,
                            FloorId = 18,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 177,
                            FloorId = 18,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 178,
                            FloorId = 18,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 179,
                            FloorId = 18,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 180,
                            FloorId = 18,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 181,
                            FloorId = 19,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 182,
                            FloorId = 19,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 183,
                            FloorId = 19,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 184,
                            FloorId = 19,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 185,
                            FloorId = 19,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 186,
                            FloorId = 19,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 187,
                            FloorId = 19,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 188,
                            FloorId = 19,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 189,
                            FloorId = 19,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 190,
                            FloorId = 19,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 191,
                            FloorId = 20,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 192,
                            FloorId = 20,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 193,
                            FloorId = 20,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 194,
                            FloorId = 20,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 195,
                            FloorId = 20,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 196,
                            FloorId = 20,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 197,
                            FloorId = 20,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 198,
                            FloorId = 20,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 199,
                            FloorId = 20,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 200,
                            FloorId = 20,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 201,
                            FloorId = 21,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 202,
                            FloorId = 21,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 203,
                            FloorId = 21,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 204,
                            FloorId = 21,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 205,
                            FloorId = 21,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 206,
                            FloorId = 21,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 207,
                            FloorId = 21,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 208,
                            FloorId = 21,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 209,
                            FloorId = 21,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 210,
                            FloorId = 21,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 211,
                            FloorId = 22,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 212,
                            FloorId = 22,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 213,
                            FloorId = 22,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 214,
                            FloorId = 22,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 215,
                            FloorId = 22,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 216,
                            FloorId = 22,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 217,
                            FloorId = 22,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 218,
                            FloorId = 22,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 219,
                            FloorId = 22,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 220,
                            FloorId = 22,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 221,
                            FloorId = 23,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 222,
                            FloorId = 23,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 223,
                            FloorId = 23,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 224,
                            FloorId = 23,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 225,
                            FloorId = 23,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 226,
                            FloorId = 23,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 227,
                            FloorId = 23,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 228,
                            FloorId = 23,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 229,
                            FloorId = 23,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 230,
                            FloorId = 23,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 231,
                            FloorId = 24,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 232,
                            FloorId = 24,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 233,
                            FloorId = 24,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 234,
                            FloorId = 24,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 235,
                            FloorId = 24,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 236,
                            FloorId = 24,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 237,
                            FloorId = 24,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 238,
                            FloorId = 24,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 239,
                            FloorId = 24,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 240,
                            FloorId = 24,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 241,
                            FloorId = 25,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 242,
                            FloorId = 25,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 243,
                            FloorId = 25,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 244,
                            FloorId = 25,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 245,
                            FloorId = 25,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 246,
                            FloorId = 25,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 247,
                            FloorId = 25,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 248,
                            FloorId = 25,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 249,
                            FloorId = 25,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 250,
                            FloorId = 25,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 251,
                            FloorId = 26,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 252,
                            FloorId = 26,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 253,
                            FloorId = 26,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 254,
                            FloorId = 26,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 255,
                            FloorId = 26,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 256,
                            FloorId = 26,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 257,
                            FloorId = 26,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 258,
                            FloorId = 26,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 259,
                            FloorId = 26,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 260,
                            FloorId = 26,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 261,
                            FloorId = 27,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 262,
                            FloorId = 27,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 263,
                            FloorId = 27,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 264,
                            FloorId = 27,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 265,
                            FloorId = 27,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 266,
                            FloorId = 27,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 267,
                            FloorId = 27,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 268,
                            FloorId = 27,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 269,
                            FloorId = 27,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 270,
                            FloorId = 27,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 271,
                            FloorId = 28,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 272,
                            FloorId = 28,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 273,
                            FloorId = 28,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 274,
                            FloorId = 28,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 275,
                            FloorId = 28,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 276,
                            FloorId = 28,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 277,
                            FloorId = 28,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 278,
                            FloorId = 28,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 279,
                            FloorId = 28,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 280,
                            FloorId = 28,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 281,
                            FloorId = 29,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 282,
                            FloorId = 29,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 283,
                            FloorId = 29,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 284,
                            FloorId = 29,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 285,
                            FloorId = 29,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 286,
                            FloorId = 29,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 287,
                            FloorId = 29,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 288,
                            FloorId = 29,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 289,
                            FloorId = 29,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 290,
                            FloorId = 29,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 291,
                            FloorId = 30,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 292,
                            FloorId = 30,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 293,
                            FloorId = 30,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 294,
                            FloorId = 30,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 295,
                            FloorId = 30,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 296,
                            FloorId = 30,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 297,
                            FloorId = 30,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 298,
                            FloorId = 30,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 299,
                            FloorId = 30,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 300,
                            FloorId = 30,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 301,
                            FloorId = 31,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 302,
                            FloorId = 31,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 303,
                            FloorId = 31,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 304,
                            FloorId = 31,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 305,
                            FloorId = 31,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 306,
                            FloorId = 31,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 307,
                            FloorId = 31,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 308,
                            FloorId = 31,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 309,
                            FloorId = 31,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 310,
                            FloorId = 31,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 311,
                            FloorId = 32,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 312,
                            FloorId = 32,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 313,
                            FloorId = 32,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 314,
                            FloorId = 32,
                            Type = (byte)1
                        },
                        new
                        {
                            Id = 315,
                            FloorId = 32,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 316,
                            FloorId = 32,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 317,
                            FloorId = 32,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 318,
                            FloorId = 32,
                            Type = (byte)2
                        },
                        new
                        {
                            Id = 319,
                            FloorId = 32,
                            Type = (byte)4
                        },
                        new
                        {
                            Id = 320,
                            FloorId = 32,
                            Type = (byte)4
                        });
                });

            modelBuilder.Entity("HotelDashboard.Data.Models.RoomStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ReserveEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReserveStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .IsUnique();

                    b.ToTable("RoomStatuses");
                });

            modelBuilder.Entity("HotelDashboard.Data.Models.Client", b =>
                {
                    b.HasOne("HotelDashboard.Data.Models.RoomStatus", "RoomStatus")
                        .WithMany("Clients")
                        .HasForeignKey("RoomStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelDashboard.Data.Models.Floor", b =>
                {
                    b.HasOne("HotelDashboard.Data.Models.Corps", "Corps")
                        .WithMany("Floors")
                        .HasForeignKey("CorpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelDashboard.Data.Models.Room", b =>
                {
                    b.HasOne("HotelDashboard.Data.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelDashboard.Data.Models.RoomStatus", b =>
                {
                    b.HasOne("HotelDashboard.Data.Models.Room", "Room")
                        .WithOne("Status")
                        .HasForeignKey("HotelDashboard.Data.Models.RoomStatus", "RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
